#include <iostream>
using namespace std;
main()
{
string name;
cout<<"Movie name : ";
cin>>name;

int aprice;
cout<<"Adult ticket price = ";
cin>>aprice;

int cprice;
cout<<"Child ticket price = ";
cin>>cprice;

int atsold;
cout<<"Enter the number of adult tickets sold = ";
cin>>atsold;

int ctsold;
cout<<"Enter the number of child tickets sold = ";
cin>>ctsold;

int c1;
c1=aprice*atsold;

int c2;
c2=cprice*ctsold;

int total;
total=c1+c2;
cout<<"Total amount generated by the total sold tickets = "<<total<<endl;

int charity;
cout<<"Percentage of amount donated to the charity = ";
cin>>charity;

int dcharity;
dcharity=total*charity/100;
cout<<"Amount donated to charity = "<<dcharity<<endl;

int profit;
profit=total-dcharity;
cout<<"Total profit = "<<profit;






}